version: '3'

networks:
  websockets:
    driver: bridge

services:
  # administration: http://localhost:15672
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3.7-management"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - websockets
    volumes:
      - "./rabbitmq:/var/lib/rabbitmq"

  redis:
    image: redis:6.2.1-alpine
    container_name: redis
#   ports:
#     - "6379:6379"
    networks:
      - websockets

  backend1:
    build: backend1/
    image: "backend1:latest"
    command: /wait-for-it.sh rabbitmq:15672 -t 30 -- /wait-for-it.sh redis:6379 -t 30 -- java -Duser.timezone=America/Sao_Paulo -Dserver.port=8080 -jar program.jar
    environment:
      SPRING_RABBITMQ_HOST: "rabbitmq"
      SPRING_RABBITMQ_PORT: "5672"
      SPRING_RABBITMQ_USERNAME: "admin"
      SPRING_RABBITMQ_PASSWORD: "admin"
      SPRING_SESSION_STORE-TYPE: "redis"
      SPRING_REDIS_HOST: "redis"
      SPRING_REDIS_PORT: "6379"
#    ports:
#      - "8080:8080"
    networks:
      - websockets
    depends_on:
      - rabbitmq
      - redis
    deploy:
      replicas: 2

  backend2:
    build: backend2/
    image: "backend2:latest"
    command: /wait-for-it.sh rabbitmq:15672 -t 30 -- java -Duser.timezone=America/Sao_Paulo -Dserver.port=8081 -jar program.jar
    environment:
      SPRING_RABBITMQ_HOST: "rabbitmq"
      SPRING_RABBITMQ_PORT: "5672"
      SPRING_RABBITMQ_USERNAME: "admin"
      SPRING_RABBITMQ_PASSWORD: "admin"
#    ports:
#      - "8081:8081"
    networks:
      - websockets
    depends_on:
      - rabbitmq
    deploy:
      replicas: 2

  app-bff:
    build: app-bff
    image: nginx-bff-proxy:latest
    container_name: food-nginx-proxy
    ports:
      - "80:80"
    networks:
      - websockets
    depends_on:
      - backend1