version: '3'

services:
  # administration: http://localhost:15672
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3.7-management"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./rabbitmq:/var/lib/rabbitmq"